import { Quiz } from '@/models/types';

export const QUIZZES: Quiz[] = [
  {
    title: 'Grammar Master Quiz: Present Tenses & Common Errors',
    slug: 'grammar-master-quiz',
    category: 'Grammar',
    difficulty: 'Intermediate',
    description: 'Test your grasp of tenses, subject-verb agreement, and tricky prepositions with instant explanations.',
    questionCount: 5,
    questions: [
      {
        id: 'q1',
        question: 'Which sentence is grammatically correct?',
        options: [
          'She go to work every day by train.',
          'She goes to work every day by train.',
          'She going to work every day by train.',
          'She has go to work every day by train.',
        ],
        correctAnswer: 1,
        explanation: 'In the Present Simple, third-person singular subjects (she, he, it) require the verb to end with -s or -es ("goes").',
      },
      {
        id: 'q2',
        question: 'Look outside! It _______ right now.',
        options: ['rains', 'is raining', 'is rain', 'has rained'],
        correctAnswer: 1,
        explanation: '"Right now" signifies an action in progress at the exact moment of speech, requiring the Present Continuous ("is raining").',
      },
      {
        id: 'q3',
        question: 'Everyone in the meeting room _______ ready to start.',
        options: ['are', 'is', 'were', 'have been'],
        correctAnswer: 1,
        explanation: '"Everyone" is a singular indefinite pronoun and therefore agrees with the singular verb "is".',
      },
      {
        id: 'q4',
        question: 'He has lived in London _______ 2019.',
        options: ['for', 'since', 'during', 'from'],
        correctAnswer: 1,
        explanation: 'Use "since" with a specific starting date (2019) to denote when the continuous action began.',
      },
      {
        id: 'q5',
        question: 'Which sentence correctly uses indefinite articles?',
        options: [
          'He waited for a hour at the station.',
          'He waited for an hour at the station.',
          'He waited for the hour at the station.',
          'He waited for one hour at the station.',
        ],
        correctAnswer: 1,
        explanation: '"Hour" begins with a silent \'h\', producing an initial vowel sound (/aʊ/), which requires "an".',
      },
    ],
  },
  {
    title: 'Vocabulary & Lexicon Challenge: Professional & Everyday Words',
    slug: 'vocabulary-lexicon-challenge',
    category: 'Vocabulary',
    difficulty: 'Intermediate',
    description: 'Challenge your understanding of high-frequency words, professional adjectives, and idioms.',
    questionCount: 4,
    questions: [
      {
        id: 'vq1',
        question: 'What is the definition of "Pragmatic"?',
        options: [
          'Emotional and highly dramatic',
          'Dealing with matters realistically and practically',
          'Hesitant to participate in discussions',
          'Completely theoretical and unproven',
        ],
        correctAnswer: 1,
        explanation: 'Pragmatic describes a person or approach that is guided by practical, realistic considerations rather than theory.',
      },
      {
        id: 'vq2',
        question: 'Choose the correct synonym for "Articulate":',
        options: ['Confused', 'Eloquent & Clear', 'Hesitant', 'Quiet'],
        correctAnswer: 1,
        explanation: '"Articulate" means able to express thoughts and ideas clearly and effectively in speech or writing.',
      },
      {
        id: 'vq3',
        question: 'What does the idiom "to play it by ear" mean?',
        options: [
          'To listen carefully to audio recordings',
          'To make decisions spontaneously according to circumstances rather than following a fixed plan',
          'To play musical instruments proficiently',
          'To ignore advice from others',
        ],
        correctAnswer: 1,
        explanation: '"Play it by ear" is an idiom meaning to proceed spontaneously and see how things develop.',
      },
      {
        id: 'vq4',
        question: 'Which word correctly completes: "Her positive attitude _______ the entire team."?',
        options: ['effected', 'affected', 'infecting', 'affectionate'],
        correctAnswer: 1,
        explanation: 'Here we need a past tense verb meaning "influenced", which is "affected".',
      },
    ],
  },
  {
    title: 'Spoken English & Workplace Etiquette Quiz',
    slug: 'spoken-english-workplace-quiz',
    category: 'Speaking',
    difficulty: 'Beginner',
    description: 'Test your fluency in everyday conversation, professional email phrasing, and meeting dialogues.',
    questionCount: 3,
    questions: [
      {
        id: 'sq1',
        question: 'How should you politely ask someone to explain something further in a business meeting?',
        options: [
          'Explain me now!',
          'Could you unpack that point a bit further?',
          'What are you saying?',
          'I want an explanation.',
        ],
        correctAnswer: 1,
        explanation: '"Could you unpack that point a bit further?" is a polite, professional, and standard idiom used in business meetings.',
      },
      {
        id: 'sq2',
        question: 'Which is the natural English response to "How are you doing?"',
        options: [
          'I am doing nothing.',
          'Pretty good, thanks! How about you?',
          'Yes, I do.',
          'I have fine.',
        ],
        correctAnswer: 1,
        explanation: '"Pretty good, thanks! How about you?" is the most natural, friendly response in modern English conversational etiquette.',
      },
      {
        id: 'sq3',
        question: 'Complete the sentence: "I look forward to _______ from you soon."',
        options: ['hear', 'hearing', 'heard', 'be hearing'],
        correctAnswer: 1,
        explanation: 'In the phrasal construction "look forward to", "to" functions as a preposition, requiring the gerund "hearing".',
      },
    ],
  },
  {
    title: 'Pronunciation & Intonation Master Test',
    slug: 'pronunciation-intonation-test',
    category: 'Pronunciation',
    difficulty: 'Intermediate',
    description: 'Test your grasp of the voiced vs voiceless TH, silent letters, and noun vs verb word stress.',
    questionCount: 3,
    questions: [
      {
        id: 'pq1',
        question: 'In which of the following words is the "TH" sound voiced (vocal cords vibrate)?',
        options: ['Think', 'Thursday', 'Breathe', 'Bath'],
        correctAnswer: 2,
        explanation: 'In the verb "breathe" /briːð/, the TH is voiced, unlike in "think", "Thursday", or "bath" which are voiceless (/θ/).',
      },
      {
        id: 'pq2',
        question: 'Which word contains a silent "B"?',
        options: ['Table', 'Doubt', 'Robber', 'Cabinet'],
        correctAnswer: 1,
        explanation: 'In the word "doubt" (/daʊt/), the letter "B" is completely silent.',
      },
      {
        id: 'pq3',
        question: 'When "present" is used as a verb (e.g. to present a report), where does the stress go?',
        options: ['First syllable (PRE-sent)', 'Second syllable (pre-SENT)', 'Both syllables equally', 'Neither syllable'],
        correctAnswer: 1,
        explanation: 'Two-syllable verbs in English typically stress the second syllable (pre-SENT), whereas nouns stress the first (PRE-sent).',
      },
    ],
  },
  {
    title: 'Common Mistakes & False Friends Challenge',
    slug: 'common-mistakes-challenge',
    category: 'Common Mistakes',
    difficulty: 'Intermediate',
    description: 'Avoid tricky translation traps, confusing words, and preposition errors.',
    questionCount: 3,
    questions: [
      {
        id: 'cm1',
        question: 'Choose the correct preposition: "I was born _______ October 15th, 1998."',
        options: ['in', 'at', 'on', 'from'],
        correctAnswer: 2,
        explanation: 'Specific calendar dates take the preposition "on" (e.g., on October 15th).',
      },
      {
        id: 'cm2',
        question: 'What does the English word "actually" mean?',
        options: ['At the present moment', 'In reality / in fact', 'Quickly and easily', 'Occasionally'],
        correctAnswer: 1,
        explanation: '"Actually" means "in reality" or "in truth". It is a false friend in many European languages where similar words mean "currently".',
      },
      {
        id: 'cm3',
        question: 'Which sentence correctly uses "fewer" vs "less"?',
        options: [
          'There are less people in the room today.',
          'There are fewer people in the room today.',
          'She has fewer time to finish the work.',
          'He made less mistakes than yesterday.',
        ],
        correctAnswer: 1,
        explanation: 'Use "fewer" with countable plural nouns like "people" and "mistakes". Use "less" with uncountable nouns like "time".',
      },
    ],
  },
];
